{{- if .Values.env.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.deployment.name }}"
  namespace: {{ .Values.namespace | quote }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.env.secret.data }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
{{- end -}}