# Default values for payfi-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Deployment
deployment:
  image: "nginx"
  tag: "latest"
  pullPolicy: IfNotPresent
  replicas: 1
  port: 80
  name: "nginx"

#Namespace
namespace: "default"

# Resources
resources:
  limits:
    cpu: "100m"
    memory: "100Mi"
  requests:
    cpu: "100m"
    memory: "100Mi"

# Environment
environment: {}
# uncomment name below to set environment variables to `Staging` or `Production`. Development does not have a label
# Must be set to `Production` for production deployments and `Staging` for staging deployments.
#   name: "Staging | Production"

# Tolerations
tolerations:
  enabled: false # set to `false` for development alone. Must be `true` for Staging and Production

# Service
service:
  type: NodePort
  protocol:
    name: TCP
    http: 80
    https: 443

# Environment Variables sources
env:
  secret:
    # set to `true` to create a secret with the environment variables. Secret name is same with the deployment name.
    # data should contain key value pairs in the format of "key":"value".
    create: false
    data: 
      {}
  configmap:
    # set to `true` to create a configmap with the environment variables. Configmap name is same with the deployment name.
    # data should contain key value pairs in the format of "key":"value".
    create: false 
    data: 
      {}

# autoscaling
# This is used for scaling pods horizontally.

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# persistent volume
pv:
  # uncomment below to set persistent volume
  create: false # true: create pv | false: do not create pvc
  name: "payfi-pv"
  size: 128Gi
  path: "/var/lib/payfi"
  storageClass: "gp2"

# persistent volume claim
pvc:
  create: false # true: create pvc | false: do not create pvc
  name: "payfi-pvc"
  size: 128Gi
  storageClass: "gp2"